### ISSUE TITLE
Utility function to read samples from a file

### ISSUE THREAD

**Issue by lkosmid** [federeghe/chronovise#15]
In the [simple_hello_world_cv_2.cpp](https://github.com/federeghe/chronovise/blob/master/samples/simple_hello_world_cv_2.cpp) example the time samples are provided statically in an array defined in the [test_cv_values.h](https://github.com/federeghe/chronovise/blob/master/samples/test_cv_values.h) header file. However, this means that the program has to be recompiled every time in order to be used with a new data set.

In order chronovise to be easier to use by end-users (e.g. engineers not developers) , it would be useful to provide a utility function that can parse directly an input file such as [test_cv_values.txt](https://github.com/federeghe/chronovise/blob/master/samples/test_cv_values.txt). Moreover, this will provide compatibility with MBPTA-CV.

**Comment by federeghe** [comment]
You're right, this was a very ugly hack just for the review. However, in C++ it's very easy to read numbers from a file using `ifstream`, declaring somewhere (let's say global)

```
std::ifstream my_input_file ("file.txt"); 
```

and then in `onRun()` doing something like this:

```
float num;
my_input_file >> num;
this->add_sample(num);
```

I didn't put too much effort in that example, because the user is required to implement the class `SimpleExecutionContext` or `ExecutionContext` as he or she desires, but I can fix this horrible hack.

**Comment by lkosmid** [comment]
What I was thinking is that instead of modifying the example, to overload add_sample() in order to get a filename as an argument, since this might be a frequently used feature.

**Comment by federeghe** [comment]
Ok, I created an utility to read files (4a6a5730)  and a function add_sample_from_file() in SimpleExecutionContext (a4cc916ec). The example has been modified accordingly. I didn't use the overload to avoid name hiding problem of the parent class methods.
